# Generated by Django 2.0.3 on 2018-04-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Computer'),
        ),
    ]
