# Generated by Django 2.0.3 on 2018-04-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='dr_user',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='software',
            name='computer',
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
        migrations.DeleteModel(
            name='DR_User',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
    ]
