# Generated by Django 2.0.3 on 2018-04-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desks', '0002_auto_20180409_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=10)),
                ('address', models.GenericIPAddressField()),
                ('displays', models.IntegerField(default=2)),
                ('ram', models.IntegerField(default=0)),
                ('cpu', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('desk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='desks.Desk')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('computer', models.ManyToManyField(to='computers.Computer')),
            ],
        ),
    ]
