# Generated by Django 2.0.3 on 2018-04-02 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='user',
        ),
        migrations.AddField(
            model_name='desk',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desk',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dr_user',
            name='business_unit',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dr_user',
            name='desk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='desks.Desk'),
        ),
    ]
