# Generated by Django 2.0.3 on 2018-04-03 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0002_auto_20180403_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='cpu',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='displays',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
