# Generated by Django 2.0.3 on 2018-04-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desks', '0003_auto_20180403_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='displays',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='desk',
            name='data_points',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='desk',
            name='power_points',
            field=models.IntegerField(default=10),
        ),
    ]
