# Generated by Django 2.0.3 on 2018-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_desk_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='druser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='druser',
            name='modified',
        ),
        migrations.AlterField(
            model_name='druser',
            name='username',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
