# Generated by Django 2.0.3 on 2018-04-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20180412_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='modified',
        ),
    ]
