# Generated by Django 2.0.3 on 2018-04-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20180413_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='computer',
        ),
        migrations.AddField(
            model_name='software',
            name='computer',
            field=models.ForeignKey(default='SYDWJYN4GY1', on_delete=django.db.models.deletion.CASCADE, to='room.Computer'),
            preserve_default=False,
        ),
    ]
