# Generated by Django 2.0.3 on 2018-04-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20180417_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='vendor',
        ),
    ]
